name: stat2dyn
channels:
- conda-forge
- fastai
- nvidia
- pytorch
dependencies:
- _libgcc_mutex=0.1=conda_forge
- _openmp_mutex=4.5=2_kmp_llvm
- absl-py=2.1.0=pyhd8ed1ab_0
- accelerate=0.31.0=pyhd8ed1ab_0
- alsa-lib=1.2.12=h4ab18f5_0
- antlr-python-runtime=4.9.3=pyhd8ed1ab_1
- anyio=4.4.0=pyhd8ed1ab_0
- aom=3.9.1=hac33072_0
- appdirs=1.4.4=pyh9f0ad1d_0
- argon2-cffi=23.1.0=pyhd8ed1ab_0
- argon2-cffi-bindings=21.2.0=py311h459d7ec_4
- arrow=1.3.0=pyhd8ed1ab_0
- astroid=3.2.2=py311h38be061_0
- asttokens=2.4.1=pyhd8ed1ab_0
- async-lru=2.0.4=pyhd8ed1ab_0
- attr=2.5.1=h166bdaf_1
- attrs=23.2.0=pyh71513ae_0
- babel=2.14.0=pyhd8ed1ab_0
- beautifulsoup4=4.12.3=pyha770c72_0
- blas=1.0=mkl
- bleach=6.1.0=pyhd8ed1ab_0
- blessed=1.19.1=pyhe4f9e05_2
- blosc=1.21.5=hc2324a3_1
- brotli=1.1.0=hd590300_1
- brotli-bin=1.1.0=hd590300_1
- brotli-python=1.1.0=py311hb755f60_1
- brunsli=0.1=h9c3ff4c_0
- bzip2=1.0.8=hd590300_5
- c-ares=1.28.1=hd590300_0
- c-blosc2=2.14.4=hb4ffafa_1
- ca-certificates=2024.7.4=hbcca054_0
- cached-property=1.5.2=hd8ed1ab_1
- cached_property=1.5.2=pyha770c72_1
- cairo=1.18.0=h3faef2a_0
- certifi=2024.6.2=pyhd8ed1ab_0
- cffi=1.16.0=py311hb3a22ac_0
- cfgv=3.3.1=pyhd8ed1ab_0
- charls=2.4.2=h59595ed_0
- charset-normalizer=3.3.2=pyhd8ed1ab_0
- click=8.1.7=unix_pyh707e725_0
- cloudpickle=3.0.0=pyhd8ed1ab_0
- colorama=0.4.6=pyhd8ed1ab_0
- colorlog=6.8.2=py311h38be061_0
- comm=0.2.2=pyhd8ed1ab_0
- contourpy=1.2.1=py311h9547e67_0
- cuda-cudart=12.1.105=0
- cuda-cupti=12.1.105=0
- cuda-libraries=12.1.0=0
- cuda-nvrtc=12.1.105=0
- cuda-nvtx=12.1.105=0
- cuda-opencl=12.5.39=0
- cuda-runtime=12.1.0=0
- cuda-version=12.5=3
- cycler=0.12.1=pyhd8ed1ab_0
- dataclasses=0.8=pyhc8e2a94_3
- dav1d=1.2.1=hd590300_0
- dbus=1.13.6=h5008d03_3
- debugpy=1.8.2=py311h4332511_0
- decorator=5.1.1=pyhd8ed1ab_0
- defusedxml=0.7.1=pyhd8ed1ab_0
- diffusers=0.29.2=pyhd8ed1ab_0
- dill=0.3.8=pyhd8ed1ab_0
- distlib=0.3.8=pyhd8ed1ab_0
- docker-pycreds=0.4.0=py_0
- enlighten=1.12.4=pyhd8ed1ab_0
- entrypoints=0.4=pyhd8ed1ab_0
- exceptiongroup=1.2.0=pyhd8ed1ab_2
- executing=2.0.1=pyhd8ed1ab_0
- expat=2.6.2=h59595ed_0
- ffmpeg=6.1.1=gpl_h5f74e41_109
- filelock=3.15.4=pyhd8ed1ab_0
- font-ttf-dejavu-sans-mono=2.37=hab24e00_0
- font-ttf-inconsolata=3.000=h77eed37_0
- font-ttf-source-code-pro=2.038=h77eed37_0
- font-ttf-ubuntu=0.83=h77eed37_2
- fontconfig=2.14.2=h14ed4e7_0
- fonts-conda-ecosystem=1=0
- fonts-conda-forge=1=0
- fonttools=4.53.0=py311h331c9d8_0
- fqdn=1.5.1=pyhd8ed1ab_0
- freetype=2.12.1=h267a509_2
- fribidi=1.0.10=h36c2ea0_0
- fsspec=2024.6.1=pyhff2d567_0
- gettext=0.22.5=h59595ed_2
- gettext-tools=0.22.5=h59595ed_2
- giflib=5.2.2=hd590300_0
- gitdb=4.0.11=pyhd8ed1ab_0
- gitpython=3.1.43=pyhd8ed1ab_0
- glib=2.80.2=hf974151_0
- glib-tools=2.80.2=hb6ce0ca_0
- gmp=6.3.0=hac33072_2
- gmpy2=2.1.5=py311hc4f1f91_1
- gnutls=3.7.9=hb077bed_0
- graphite2=1.3.13=h59595ed_1003
- grpcio=1.62.2=py311ha6695c7_0
- gst-plugins-base=1.24.4=h9ad1361_0
- gstreamer=1.24.4=haf2f30d_0
- h11=0.14.0=pyhd8ed1ab_0
- h2=4.1.0=pyhd8ed1ab_0
- harfbuzz=8.5.0=hfac3d4d_0
- hpack=4.0.0=pyh9f0ad1d_0
- httpcore=1.0.5=pyhd8ed1ab_0
- httpx=0.27.0=pyhd8ed1ab_0
- huggingface_hub=0.23.4=pyhd8ed1ab_0
- hydra-colorlog=1.2.0=pyhd8ed1ab_1
- hydra-core=1.3.2=pyhd8ed1ab_0
- hydra-zen=0.13.0=pyhd8ed1ab_0
- hyperframe=6.0.1=pyhd8ed1ab_0
- icu=73.2=h59595ed_0
- identify=2.5.36=pyhd8ed1ab_0
- idna=3.7=pyhd8ed1ab_0
- imagecodecs=2024.6.1=py311h60053b1_0
- imageio=2.34.2=pyh12aca89_0
- imageio-ffmpeg=0.5.1=pyhd8ed1ab_0
- importlib-metadata=8.0.0=pyha770c72_0
- importlib_metadata=8.0.0=hd8ed1ab_0
- importlib_resources=6.4.0=pyhd8ed1ab_0
- ipdb=0.13.13=pyhd8ed1ab_0
- ipykernel=6.29.5=pyh3099207_0
- ipympl=0.9.4=pyhd8ed1ab_0
- ipython=8.26.0=pyh707e725_0
- ipython_genutils=0.2.0=py_1
- ipywidgets=8.1.3=pyhd8ed1ab_0
- isoduration=20.11.0=pyhd8ed1ab_0
- isort=5.13.2=pyhd8ed1ab_0
- jedi=0.19.1=pyhd8ed1ab_0
- jinja2=3.1.4=pyhd8ed1ab_0
- joblib=1.4.2=pyhd8ed1ab_0
- json5=0.9.25=pyhd8ed1ab_0
- jsonpointer=3.0.0=py311h38be061_0
- jsonschema=4.22.0=pyhd8ed1ab_0
- jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
- jsonschema-with-format-nongpl=4.22.0=pyhd8ed1ab_0
- jupyter=1.0.0=pyhd8ed1ab_10
- jupyter-lsp=2.2.5=pyhd8ed1ab_0
- jupyter_client=8.6.2=pyhd8ed1ab_0
- jupyter_console=6.6.3=pyhd8ed1ab_0
- jupyter_core=5.7.2=py311h38be061_0
- jupyter_events=0.10.0=pyhd8ed1ab_0
- jupyter_server=2.14.1=pyhd8ed1ab_0
- jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
- jupyterlab=4.2.3=pyhd8ed1ab_0
- jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
- jupyterlab_server=2.27.2=pyhd8ed1ab_0
- jupyterlab_widgets=3.0.11=pyhd8ed1ab_0
- jxrlib=1.1=hd590300_3
- kaleido-core=0.2.1=h3644ca4_0
- keyutils=1.6.1=h166bdaf_0
- kiwisolver=1.4.5=py311h9547e67_1
- krb5=1.21.3=h659f571_0
- lame=3.100=h166bdaf_1003
- lcms2=2.16=hb7c19ff_0
- ld_impl_linux-64=2.40=hf3520f5_7
- lerc=4.0.0=h27087fc_0
- libabseil=20240116.2=cxx17_h59595ed_0
- libaec=1.1.3=h59595ed_0
- libasprintf=0.22.5=h661eb56_2
- libasprintf-devel=0.22.5=h661eb56_2
- libass=0.17.1=h8fe9dca_1
- libavif16=1.0.4=hfa3d5b6_3
- libblas=3.9.0=1_h86c2bf4_netlib
- libbrotlicommon=1.1.0=hd590300_1
- libbrotlidec=1.1.0=hd590300_1
- libbrotlienc=1.1.0=hd590300_1
- libcap=2.69=h0f662aa_0
- libcblas=3.9.0=6_ha36c22a_netlib
- libclang-cpp15=15.0.7=default_h127d8a8_5
- libclang13=18.1.7=default_h087397f_0
- libcublas=12.1.0.26=0
- libcufft=11.0.2.4=0
- libcufile=1.10.0.4=0
- libcups=2.3.3=h4637d8d_4
- libcurand=10.3.6.39=0
- libcusolver=11.4.4.55=0
- libcusparse=12.0.2.55=0
- libdeflate=1.20=hd590300_0
- libdrm=2.4.122=h4ab18f5_0
- libedit=3.1.20191231=he28a2e2_2
- libevent=2.1.12=hf998b51_1
- libexpat=2.6.2=h59595ed_0
- libffi=3.4.2=h7f98852_5
- libflac=1.4.3=h59595ed_0
- libgcc-ng=14.1.0=h77fa898_0
- libgcrypt=1.11.0=h4ab18f5_0
- libgettextpo=0.22.5=h59595ed_2
- libgettextpo-devel=0.22.5=h59595ed_2
- libgfortran-ng=14.1.0=h69a702a_0
- libgfortran5=14.1.0=hc5f4f2c_0
- libglib=2.80.2=hf974151_0
- libgpg-error=1.50=h4f305b6_0
- libgrpc=1.62.2=h15f2491_0
- libhwloc=2.11.0=default_h5622ce7_1000
- libhwy=1.1.0=h00ab1b0_0
- libiconv=1.17=hd590300_2
- libidn2=2.3.7=hd590300_0
- libjpeg-turbo=3.0.0=hd590300_1
- libjxl=0.10.2=hcae5a98_0
- liblapack=3.9.0=6_ha36c22a_netlib
- libllvm15=15.0.7=hb3ce162_4
- libllvm18=18.1.7=hb77312f_0
- libnpp=12.0.2.50=0
- libnsl=2.0.1=hd590300_0
- libnvfatbin=12.5.39=0
- libnvjitlink=12.1.105=0
- libnvjpeg=12.1.1.14=0
- libogg=1.3.5=h4ab18f5_0
- libopenvino=2024.0.0=h2da1b83_5
- libopenvino-auto-batch-plugin=2024.0.0=hb045406_5
- libopenvino-auto-plugin=2024.0.0=hb045406_5
- libopenvino-hetero-plugin=2024.0.0=h5c03a75_5
- libopenvino-intel-cpu-plugin=2024.0.0=h2da1b83_5
- libopenvino-intel-gpu-plugin=2024.0.0=h2da1b83_5
- libopenvino-ir-frontend=2024.0.0=h5c03a75_5
- libopenvino-onnx-frontend=2024.0.0=h07e8aee_5
- libopenvino-paddle-frontend=2024.0.0=h07e8aee_5
- libopenvino-pytorch-frontend=2024.0.0=he02047a_5
- libopenvino-tensorflow-frontend=2024.0.0=h39126c6_5
- libopenvino-tensorflow-lite-frontend=2024.0.0=he02047a_5
- libopus=1.3.1=h7f98852_1
- libpciaccess=0.18=hd590300_0
- libpng=1.6.43=h2797004_0
- libpq=16.3=ha72fbe1_0
- libprotobuf=4.25.3=h08a7969_0
- libre2-11=2023.09.01=h5a48ba9_2
- libsndfile=1.2.2=hc60ed4a_1
- libsodium=1.0.18=h36c2ea0_1
- libsqlite=3.46.0=hde9e2c9_0
- libstdcxx-ng=14.1.0=hc0a3c3a_0
- libsystemd0=255=h3516f8a_1
- libtasn1=4.19.0=h166bdaf_0
- libtiff=4.6.0=h1dd3fc0_3
- libunistring=0.9.10=h7f98852_0
- libuuid=2.38.1=h0b41bf4_0
- libva=2.21.0=h4ab18f5_2
- libvorbis=1.3.7=h9c3ff4c_0
- libvpx=1.14.1=hac33072_0
- libwebp-base=1.4.0=hd590300_0
- libxcb=1.15=h0b41bf4_0
- libxcrypt=4.4.36=hd590300_1
- libxkbcommon=1.7.0=h662e7e4_0
- libxml2=2.12.7=hc051c1a_1
- libzlib=1.2.13=h4ab18f5_6
- libzopfli=1.0.3=h9c3ff4c_0
- llvm-openmp=15.0.7=h0cdce71_0
- lz4-c=1.9.4=hcb278e6_0
- markdown=3.6=pyhd8ed1ab_0
- markdown-it-py=3.0.0=pyhd8ed1ab_0
- markupsafe=2.1.5=py311h459d7ec_0
- mathjax=2.7.7=ha770c72_3
- matplotlib=3.9.0=py311h38be061_0
- matplotlib-base=3.9.0=py311hffb96ce_0
- matplotlib-inline=0.1.7=pyhd8ed1ab_0
- mccabe=0.7.0=pyhd8ed1ab_0
- mdurl=0.1.2=pyhd8ed1ab_0
- mistune=3.0.2=pyhd8ed1ab_0
- mkl=2023.0.0=h84fe81f_26648
- moviepy=1.0.3=pyhd8ed1ab_1
- mpc=1.3.1=hfe3b2da_0
- mpfr=4.2.1=h9458935_1
- mpg123=1.32.6=h59595ed_0
- mpmath=1.3.0=pyhd8ed1ab_0
- munkres=1.1.4=pyh9f0ad1d_0
- mysql-common=8.3.0=hf1915f5_4
- mysql-libs=8.3.0=hca2cd23_4
- nbclient=0.10.0=pyhd8ed1ab_0
- nbconvert=7.16.4=hd8ed1ab_1
- nbconvert-core=7.16.4=pyhd8ed1ab_1
- nbconvert-pandoc=7.16.4=hd8ed1ab_1
- nbformat=5.10.4=pyhd8ed1ab_0
- ncurses=6.5=h59595ed_0
- nest-asyncio=1.6.0=pyhd8ed1ab_0
- nettle=3.9.1=h7ab15ed_0
- networkx=3.3=pyhd8ed1ab_1
- nodeenv=1.9.1=pyhd8ed1ab_0
- notebook=7.2.1=pyhd8ed1ab_0
- notebook-shim=0.2.4=pyhd8ed1ab_0
- nspr=4.35=h27087fc_0
- nss=3.100=hca3bf56_0
- numpy=1.26.4=py311h64a7726_0
- ocl-icd=2.3.2=hd590300_1
- omegaconf=2.3.0=pyhd8ed1ab_0
- opencv-python-headless=4.10.0.84=py311_0
- openh264=2.4.1=h59595ed_0
- openjpeg=2.5.2=h488ebb8_0
- openssl=3.3.1=h4ab18f5_1
- overrides=7.7.0=pyhd8ed1ab_0
- p11-kit=0.24.1=hc5aa10d_0
- packaging=24.1=pyhd8ed1ab_0
- pandas=2.2.2=py311h14de704_1
- pandoc=3.2.1=ha770c72_0
- pandocfilters=1.5.0=pyhd8ed1ab_0
- parso=0.8.4=pyhd8ed1ab_0
- pathtools=0.1.2=py_1
- patsy=0.5.6=pyhd8ed1ab_0
- pcre2=10.43=hcad00b1_0
- pexpect=4.9.0=pyhd8ed1ab_0
- pickleshare=0.7.5=py_1003
- pillow=10.3.0=py311h18e6fac_0
- pip=24.0=pyhd8ed1ab_0
- pixman=0.43.2=h59595ed_0
- pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
- platformdirs=4.2.2=pyhd8ed1ab_0
- plotly=5.22.0=pyhd8ed1ab_0
- ply=3.11=pyhd8ed1ab_2
- pre-commit=3.7.1=pyha770c72_0
- prefixed=0.7.1=pyhd8ed1ab_0
- proglog=0.1.9=py_0
- prometheus_client=0.20.0=pyhd8ed1ab_0
- prompt-toolkit=3.0.47=pyha770c72_0
- prompt_toolkit=3.0.47=hd8ed1ab_0
- protobuf=4.25.3=py311h7b78aeb_0
- psutil=6.0.0=py311h331c9d8_0
- pthread-stubs=0.4=h36c2ea0_1001
- ptyprocess=0.7.0=pyhd3deb0d_0
- pugixml=1.14=h59595ed_0
- pulseaudio-client=17.0=hb77b528_0
- pure_eval=0.2.2=pyhd8ed1ab_0
- pycparser=2.22=pyhd8ed1ab_0
- pygments=2.18.0=pyhd8ed1ab_0
- pylint=3.2.5=pyhd8ed1ab_0
- pyparsing=3.1.2=pyhd8ed1ab_0
- pyqt=5.15.9=py311hf0fb5b6_5
- pyqt5-sip=12.12.2=py311hb755f60_5
- pysocks=1.7.1=pyha2e5f31_6
- python=3.11.9=hb806964_0_cpython
- python-dateutil=2.9.0=pyhd8ed1ab_0
- python-fastjsonschema=2.20.0=pyhd8ed1ab_0
- python-json-logger=2.0.7=pyhd8ed1ab_0
- python-kaleido=0.2.1=pyhd8ed1ab_0
- python-tzdata=2024.1=pyhd8ed1ab_0
- python_abi=3.11=4_cp311
- pytorch=2.3.1=py3.11_cuda12.1_cudnn8.9.2_0
- pytorch-cuda=12.1=ha16c6d3_5
- pytorch-mutex=1.0=cuda
- pytz=2024.1=pyhd8ed1ab_0
- pyyaml=6.0.1=py311h459d7ec_1
- pyzmq=26.0.3=py311h08a0b41_0
- qhull=2020.2=h4bd325d_2
- qt-main=5.15.8=hc9dc06e_21
- qtconsole-base=5.5.2=pyha770c72_0
- qtpy=2.4.1=pyhd8ed1ab_0
- rav1e=0.6.6=he8a937b_2
- re2=2023.09.01=h7f4b329_2
- readline=8.2=h8228510_1
- referencing=0.35.1=pyhd8ed1ab_0
- regex=2024.5.15=py311h331c9d8_0
- requests=2.32.3=pyhd8ed1ab_0
- rfc3339-validator=0.1.4=pyhd8ed1ab_0
- rfc3986-validator=0.1.1=pyh9f0ad1d_0
- rich=13.7.1=pyhd8ed1ab_0
- rpds-py=0.18.1=py311h5ecf98a_0
- ruff=0.5.0=py311hae69bc3_0
- safetensors=0.4.3=py311h46250e7_0
- scipy=1.14.0=py311h517d4fd_0
- seaborn=0.13.2=hd8ed1ab_2
- seaborn-base=0.13.2=pyhd8ed1ab_2
- send2trash=1.8.3=pyh0d859eb_0
- sentry-sdk=2.7.1=pyhd8ed1ab_0
- setproctitle=1.3.3=py311h459d7ec_0
- setuptools=70.1.1=pyhd8ed1ab_0
- sip=6.7.12=py311hb755f60_0
- six=1.16.0=pyh6c4a22f_0
- smmap=5.0.0=pyhd8ed1ab_0
- snappy=1.2.1=ha2e4443_0
- sniffio=1.3.1=pyhd8ed1ab_0
- soupsieve=2.5=pyhd8ed1ab_1
- sqlite=3.46.0=h6d4b2fc_0
- stack_data=0.6.2=pyhd8ed1ab_0
- statsmodels=0.14.2=py311h18e1886_0
- submitit=1.5.1=pyhd8ed1ab_0
- svt-av1=2.0.0=h59595ed_0
- sympy=1.12.1=pypyh2585a3b_103
- tbb=2021.12.0=h434a139_2
- tenacity=8.4.2=pyhd8ed1ab_0
- tensorboard=2.17.0=pyhd8ed1ab_0
- tensorboard-data-server=0.7.0=py311h63ff55d_1
- termcolor=2.4.0=pyhd8ed1ab_0
- terminado=0.18.1=pyh0d859eb_0
- tifffile=2024.7.2=pyhd8ed1ab_0
- tinycss2=1.3.0=pyhd8ed1ab_0
- tk=8.6.13=noxft_h4845f30_101
- toml=0.10.2=pyhd8ed1ab_0
- tomli=2.0.1=pyhd8ed1ab_0
- tomlkit=0.12.5=pyha770c72_0
- torchinfo=1.8.0=pyhd8ed1ab_0
- torchtriton=2.3.1=py311
- torchvision=0.18.1=py311_cu121
- tornado=6.4.1=py311h331c9d8_0
- tqdm=4.66.4=pyhd8ed1ab_0
- traitlets=5.14.3=pyhd8ed1ab_0
- types-python-dateutil=2.9.0.20240316=pyhd8ed1ab_0
- typing-extensions=4.12.2=hd8ed1ab_0
- typing_extensions=4.12.2=pyha770c72_0
- typing_utils=0.1.0=pyhd8ed1ab_0
- tzdata=2024a=h0c530f3_0
- ukkonen=1.0.1=py311h9547e67_4
- uri-template=1.3.0=pyhd8ed1ab_0
- urllib3=2.2.2=pyhd8ed1ab_1
- virtualenv=20.26.3=pyhd8ed1ab_0
- wcwidth=0.2.13=pyhd8ed1ab_0
- webcolors=24.6.0=pyhd8ed1ab_0
- webencodings=0.5.1=pyhd8ed1ab_2
- websocket-client=1.8.0=pyhd8ed1ab_0
- werkzeug=3.0.3=pyhd8ed1ab_0
- wheel=0.43.0=pyhd8ed1ab_1
- widgetsnbextension=4.0.11=pyhd8ed1ab_0
- x264=1!164.3095=h166bdaf_2
- x265=3.5=h924138e_3
- xcb-util=0.4.0=hd590300_1
- xcb-util-image=0.4.0=h8ee46fc_1
- xcb-util-keysyms=0.4.0=h8ee46fc_1
- xcb-util-renderutil=0.3.9=hd590300_1
- xcb-util-wm=0.4.1=h8ee46fc_1
- xkeyboard-config=2.42=h4ab18f5_0
- xorg-fixesproto=5.0=h7f98852_1002
- xorg-kbproto=1.0.7=h7f98852_1002
- xorg-libice=1.1.1=hd590300_0
- xorg-libsm=1.2.4=h7391055_0
- xorg-libx11=1.8.9=h8ee46fc_0
- xorg-libxau=1.0.11=hd590300_0
- xorg-libxdmcp=1.1.3=h7f98852_0
- xorg-libxext=1.3.4=h0b41bf4_2
- xorg-libxfixes=5.0.3=h7f98852_1004
- xorg-libxrender=0.9.11=hd590300_0
- xorg-renderproto=0.11.1=h7f98852_1002
- xorg-xextproto=7.3.0=h0b41bf4_1003
- xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
- xorg-xproto=7.0.31=h7f98852_1007
- xz=5.2.6=h166bdaf_0
- yaml=0.2.5=h7f98852_2
- zeromq=4.3.5=h75354e8_4
- zfp=1.0.1=hac33072_1
- zipp=3.19.2=pyhd8ed1ab_0
- zlib=1.2.13=h4ab18f5_6
- zlib-ng=2.0.7=h0b41bf4_0
- zstandard=0.22.0=py311hb6f056b_1
- zstd=1.5.6=ha6fb4c9_0
